// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// precompute_eigen_cache_non_common_rcpp
Rcpp::List precompute_eigen_cache_non_common_rcpp(const Rcpp::List& svs_list, const Rcpp::List& U_list);
RcppExport SEXP _mvsusieR_precompute_eigen_cache_non_common_rcpp(SEXP svs_listSEXP, SEXP U_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type svs_list(svs_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type U_list(U_listSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_eigen_cache_non_common_rcpp(svs_list, U_list));
    return rcpp_result_gen;
END_RCPP
}
// loglik_non_common_rcpp
arma::mat loglik_non_common_rcpp(const arma::mat& betahat, double V_scalar, const arma::vec& log_det_svs, const Rcpp::List& components);
RcppExport SEXP _mvsusieR_loglik_non_common_rcpp(SEXP betahatSEXP, SEXP V_scalarSEXP, SEXP log_det_svsSEXP, SEXP componentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type betahat(betahatSEXP);
    Rcpp::traits::input_parameter< double >::type V_scalar(V_scalarSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type log_det_svs(log_det_svsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type components(componentsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_non_common_rcpp(betahat, V_scalar, log_det_svs, components));
    return rcpp_result_gen;
END_RCPP
}
// posterior_non_common_rcpp
Rcpp::List posterior_non_common_rcpp(const arma::mat& betahat, double V_scalar, const Rcpp::List& components, const arma::mat& pi_V_post, const arma::mat& em_var_wt);
RcppExport SEXP _mvsusieR_posterior_non_common_rcpp(SEXP betahatSEXP, SEXP V_scalarSEXP, SEXP componentsSEXP, SEXP pi_V_postSEXP, SEXP em_var_wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type betahat(betahatSEXP);
    Rcpp::traits::input_parameter< double >::type V_scalar(V_scalarSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pi_V_post(pi_V_postSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type em_var_wt(em_var_wtSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_non_common_rcpp(betahat, V_scalar, components, pi_V_post, em_var_wt));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_mu2_common_rcpp
arma::cube accumulate_mu2_common_rcpp(arma::cube mu2, const arma::mat& M_k, const arma::mat& C_k, const arma::vec& w_k);
RcppExport SEXP _mvsusieR_accumulate_mu2_common_rcpp(SEXP mu2SEXP, SEXP M_kSEXP, SEXP C_kSEXP, SEXP w_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M_k(M_kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C_k(C_kSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_k(w_kSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_mu2_common_rcpp(mu2, M_k, C_k, w_k));
    return rcpp_result_gen;
END_RCPP
}
// loglik_common_rcpp
Rcpp::List loglik_common_rcpp(const arma::mat& betahat, double V_scalar, double log_det_svs, const Rcpp::List& components, const Rcpp::List& BQ_cache_in);
RcppExport SEXP _mvsusieR_loglik_common_rcpp(SEXP betahatSEXP, SEXP V_scalarSEXP, SEXP log_det_svsSEXP, SEXP componentsSEXP, SEXP BQ_cache_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type betahat(betahatSEXP);
    Rcpp::traits::input_parameter< double >::type V_scalar(V_scalarSEXP);
    Rcpp::traits::input_parameter< double >::type log_det_svs(log_det_svsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type BQ_cache_in(BQ_cache_inSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_common_rcpp(betahat, V_scalar, log_det_svs, components, BQ_cache_in));
    return rcpp_result_gen;
END_RCPP
}
// posterior_common_rcpp
Rcpp::List posterior_common_rcpp(const arma::mat& betahat, double V_scalar, const Rcpp::List& components, const arma::mat& pi_V_post, const arma::mat& em_var_wt, const Rcpp::List& BQ_cache_list, bool do_reduce, const arma::vec& alpha, const arma::vec& d_var, const arma::mat& v_inv);
RcppExport SEXP _mvsusieR_posterior_common_rcpp(SEXP betahatSEXP, SEXP V_scalarSEXP, SEXP componentsSEXP, SEXP pi_V_postSEXP, SEXP em_var_wtSEXP, SEXP BQ_cache_listSEXP, SEXP do_reduceSEXP, SEXP alphaSEXP, SEXP d_varSEXP, SEXP v_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type betahat(betahatSEXP);
    Rcpp::traits::input_parameter< double >::type V_scalar(V_scalarSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pi_V_post(pi_V_postSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type em_var_wt(em_var_wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type BQ_cache_list(BQ_cache_listSEXP);
    Rcpp::traits::input_parameter< bool >::type do_reduce(do_reduceSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_var(d_varSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v_inv(v_invSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_common_rcpp(betahat, V_scalar, components, pi_V_post, em_var_wt, BQ_cache_list, do_reduce, alpha, d_var, v_inv));
    return rcpp_result_gen;
END_RCPP
}
// impute_missing_Y_rcpp
List impute_missing_Y_rcpp(arma::mat Y, const arma::mat& mu, const arma::mat& Vinv, const List& patterns, const List& pattern_obs);
RcppExport SEXP _mvsusieR_impute_missing_Y_rcpp(SEXP YSEXP, SEXP muSEXP, SEXP VinvSEXP, SEXP patternsSEXP, SEXP pattern_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Vinv(VinvSEXP);
    Rcpp::traits::input_parameter< const List& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const List& >::type pattern_obs(pattern_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_missing_Y_rcpp(Y, mu, Vinv, patterns, pattern_obs));
    return rcpp_result_gen;
END_RCPP
}
// inner_em_rcpp
List inner_em_rcpp(const arma::mat& llik, const arma::vec& weights, arma::vec pi_init, int max_iter, double tol);
RcppExport SEXP _mvsusieR_inner_em_rcpp(SEXP llikSEXP, SEXP weightsSEXP, SEXP pi_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type llik(llikSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi_init(pi_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_em_rcpp(llik, weights, pi_init, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// compute_VinvR_3d_rcpp
arma::mat compute_VinvR_3d_rcpp(const arma::mat& mat, const Rcpp::List& Vinv_list, const arma::ivec& pattern_assign);
RcppExport SEXP _mvsusieR_compute_VinvR_3d_rcpp(SEXP matSEXP, SEXP Vinv_listSEXP, SEXP pattern_assignSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Vinv_list(Vinv_listSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pattern_assign(pattern_assignSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_VinvR_3d_rcpp(mat, Vinv_list, pattern_assign));
    return rcpp_result_gen;
END_RCPP
}
// compute_XtR_3d_rcpp
arma::mat compute_XtR_3d_rcpp(const arma::cube& X_3d, const arma::mat& R_mat, const Rcpp::List& Vinv_list, const arma::ivec& pattern_assign, int method, const arma::cube& Xbar);
RcppExport SEXP _mvsusieR_compute_XtR_3d_rcpp(SEXP X_3dSEXP, SEXP R_matSEXP, SEXP Vinv_listSEXP, SEXP pattern_assignSEXP, SEXP methodSEXP, SEXP XbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type X_3d(X_3dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R_mat(R_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Vinv_list(Vinv_listSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type pattern_assign(pattern_assignSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Xbar(XbarSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_XtR_3d_rcpp(X_3d, R_mat, Vinv_list, pattern_assign, method, Xbar));
    return rcpp_result_gen;
END_RCPP
}
// compute_Xb_3d_rcpp
arma::mat compute_Xb_3d_rcpp(const arma::cube& X_3d, const arma::mat& b, int method, const arma::cube& Xbar);
RcppExport SEXP _mvsusieR_compute_Xb_3d_rcpp(SEXP X_3dSEXP, SEXP bSEXP, SEXP methodSEXP, SEXP XbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type X_3d(X_3dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Xbar(XbarSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Xb_3d_rcpp(X_3d, b, method, Xbar));
    return rcpp_result_gen;
END_RCPP
}
// compute_betahat_3d_rcpp
arma::mat compute_betahat_3d_rcpp(const arma::cube& svs_3d, const arma::mat& XtR);
RcppExport SEXP _mvsusieR_compute_betahat_3d_rcpp(SEXP svs_3dSEXP, SEXP XtRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type svs_3d(svs_3dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtR(XtRSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_betahat_3d_rcpp(svs_3d, XtR));
    return rcpp_result_gen;
END_RCPP
}
// compute_svs_inv_3d_rcpp
arma::cube compute_svs_inv_3d_rcpp(const Rcpp::List& Vinv_list, const arma::imat& pattern, const arma::mat& raw_sq_sum, const arma::mat& raw_sum, const arma::ivec& n_k, const arma::mat& cm, const arma::mat& csd, int method, const arma::cube& Xbar, const arma::mat& Vinvsum);
RcppExport SEXP _mvsusieR_compute_svs_inv_3d_rcpp(SEXP Vinv_listSEXP, SEXP patternSEXP, SEXP raw_sq_sumSEXP, SEXP raw_sumSEXP, SEXP n_kSEXP, SEXP cmSEXP, SEXP csdSEXP, SEXP methodSEXP, SEXP XbarSEXP, SEXP VinvsumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Vinv_list(Vinv_listSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_sq_sum(raw_sq_sumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_sum(raw_sumSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_k(n_kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type csd(csdSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Xbar(XbarSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Vinvsum(VinvsumSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_svs_inv_3d_rcpp(Vinv_list, pattern, raw_sq_sum, raw_sum, n_k, cm, csd, method, Xbar, Vinvsum));
    return rcpp_result_gen;
END_RCPP
}
// compute_vbxxb_rcpp
Rcpp::List compute_vbxxb_rcpp(const arma::vec& alpha, const arma::cube& mu2_3d, const arma::cube& svs_inv_3d, const arma::vec& d);
RcppExport SEXP _mvsusieR_compute_vbxxb_rcpp(SEXP alphaSEXP, SEXP mu2_3dSEXP, SEXP svs_inv_3dSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type mu2_3d(mu2_3dSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type svs_inv_3d(svs_inv_3dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_vbxxb_rcpp(alpha, mu2_3d, svs_inv_3d, d));
    return rcpp_result_gen;
END_RCPP
}
// compute_Xbar_from_sums_rcpp
arma::cube compute_Xbar_from_sums_rcpp(const Rcpp::List& Vinv_list, const arma::imat& pattern, const arma::mat& raw_sum, const arma::ivec& n_k, const arma::mat& cm, const arma::mat& csd, const arma::mat& Vinvsuminv);
RcppExport SEXP _mvsusieR_compute_Xbar_from_sums_rcpp(SEXP Vinv_listSEXP, SEXP patternSEXP, SEXP raw_sumSEXP, SEXP n_kSEXP, SEXP cmSEXP, SEXP csdSEXP, SEXP VinvsuminvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Vinv_list(Vinv_listSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_sum(raw_sumSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_k(n_kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type csd(csdSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Vinvsuminv(VinvsuminvSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Xbar_from_sums_rcpp(Vinv_list, pattern, raw_sum, n_k, cm, csd, Vinvsuminv));
    return rcpp_result_gen;
END_RCPP
}
// precompute_gram_xtx_rcpp
arma::cube precompute_gram_xtx_rcpp(const arma::imat& pattern, const arma::mat& raw_sq_sum, const arma::mat& raw_sum, const arma::ivec& n_k, const arma::mat& cm, const arma::mat& csd);
RcppExport SEXP _mvsusieR_precompute_gram_xtx_rcpp(SEXP patternSEXP, SEXP raw_sq_sumSEXP, SEXP raw_sumSEXP, SEXP n_kSEXP, SEXP cmSEXP, SEXP csdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_sq_sum(raw_sq_sumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_sum(raw_sumSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type n_k(n_kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type csd(csdSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_gram_xtx_rcpp(pattern, raw_sq_sum, raw_sum, n_k, cm, csd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvsusieR_precompute_eigen_cache_non_common_rcpp", (DL_FUNC) &_mvsusieR_precompute_eigen_cache_non_common_rcpp, 2},
    {"_mvsusieR_loglik_non_common_rcpp", (DL_FUNC) &_mvsusieR_loglik_non_common_rcpp, 4},
    {"_mvsusieR_posterior_non_common_rcpp", (DL_FUNC) &_mvsusieR_posterior_non_common_rcpp, 5},
    {"_mvsusieR_accumulate_mu2_common_rcpp", (DL_FUNC) &_mvsusieR_accumulate_mu2_common_rcpp, 4},
    {"_mvsusieR_loglik_common_rcpp", (DL_FUNC) &_mvsusieR_loglik_common_rcpp, 5},
    {"_mvsusieR_posterior_common_rcpp", (DL_FUNC) &_mvsusieR_posterior_common_rcpp, 10},
    {"_mvsusieR_impute_missing_Y_rcpp", (DL_FUNC) &_mvsusieR_impute_missing_Y_rcpp, 5},
    {"_mvsusieR_inner_em_rcpp", (DL_FUNC) &_mvsusieR_inner_em_rcpp, 5},
    {"_mvsusieR_compute_VinvR_3d_rcpp", (DL_FUNC) &_mvsusieR_compute_VinvR_3d_rcpp, 3},
    {"_mvsusieR_compute_XtR_3d_rcpp", (DL_FUNC) &_mvsusieR_compute_XtR_3d_rcpp, 6},
    {"_mvsusieR_compute_Xb_3d_rcpp", (DL_FUNC) &_mvsusieR_compute_Xb_3d_rcpp, 4},
    {"_mvsusieR_compute_betahat_3d_rcpp", (DL_FUNC) &_mvsusieR_compute_betahat_3d_rcpp, 2},
    {"_mvsusieR_compute_svs_inv_3d_rcpp", (DL_FUNC) &_mvsusieR_compute_svs_inv_3d_rcpp, 10},
    {"_mvsusieR_compute_vbxxb_rcpp", (DL_FUNC) &_mvsusieR_compute_vbxxb_rcpp, 4},
    {"_mvsusieR_compute_Xbar_from_sums_rcpp", (DL_FUNC) &_mvsusieR_compute_Xbar_from_sums_rcpp, 7},
    {"_mvsusieR_precompute_gram_xtx_rcpp", (DL_FUNC) &_mvsusieR_precompute_gram_xtx_rcpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvsusieR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
