// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// impute_missing_Y_rcpp
List impute_missing_Y_rcpp(arma::mat Y, const arma::mat& mu, const arma::mat& Vinv, const List& patterns, const List& pattern_obs);
RcppExport SEXP _mvsusieR_impute_missing_Y_rcpp(SEXP YSEXP, SEXP muSEXP, SEXP VinvSEXP, SEXP patternsSEXP, SEXP pattern_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Vinv(VinvSEXP);
    Rcpp::traits::input_parameter< const List& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const List& >::type pattern_obs(pattern_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_missing_Y_rcpp(Y, mu, Vinv, patterns, pattern_obs));
    return rcpp_result_gen;
END_RCPP
}
// inner_em_cpp
List inner_em_cpp(const arma::mat& llik, const arma::vec& weights, arma::vec pi_init, int max_iter, double tol);
RcppExport SEXP _mvsusieR_inner_em_cpp(SEXP llikSEXP, SEXP weightsSEXP, SEXP pi_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type llik(llikSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi_init(pi_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_em_cpp(llik, weights, pi_init, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvsusieR_impute_missing_Y_rcpp", (DL_FUNC) &_mvsusieR_impute_missing_Y_rcpp, 5},
    {"_mvsusieR_inner_em_cpp", (DL_FUNC) &_mvsusieR_inner_em_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvsusieR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
