# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impute_missing_Y_rcpp <- function(Y, mu, Vinv, patterns, pattern_obs) {
    .Call('_mvsusieR_impute_missing_Y_rcpp', PACKAGE = 'mvsusieR', Y, mu, Vinv, patterns, pattern_obs)
}

