# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

precompute_eigen_cache_non_common_rcpp <- function(svs_list, U_list) {
    .Call('_mvsusieR_precompute_eigen_cache_non_common_rcpp', PACKAGE = 'mvsusieR', svs_list, U_list)
}

loglik_non_common_rcpp <- function(betahat, V_scalar, log_det_svs, components) {
    .Call('_mvsusieR_loglik_non_common_rcpp', PACKAGE = 'mvsusieR', betahat, V_scalar, log_det_svs, components)
}

posterior_non_common_rcpp <- function(betahat, V_scalar, components, pi_V_post, em_var_wt) {
    .Call('_mvsusieR_posterior_non_common_rcpp', PACKAGE = 'mvsusieR', betahat, V_scalar, components, pi_V_post, em_var_wt)
}

accumulate_mu2_common_rcpp <- function(mu2, M_k, C_k, w_k) {
    .Call('_mvsusieR_accumulate_mu2_common_rcpp', PACKAGE = 'mvsusieR', mu2, M_k, C_k, w_k)
}

loglik_common_rcpp <- function(betahat, V_scalar, log_det_svs, components, BQ_cache_in) {
    .Call('_mvsusieR_loglik_common_rcpp', PACKAGE = 'mvsusieR', betahat, V_scalar, log_det_svs, components, BQ_cache_in)
}

posterior_common_rcpp <- function(betahat, V_scalar, components, pi_V_post, em_var_wt, BQ_cache_list, do_reduce, alpha, d_var, v_inv) {
    .Call('_mvsusieR_posterior_common_rcpp', PACKAGE = 'mvsusieR', betahat, V_scalar, components, pi_V_post, em_var_wt, BQ_cache_list, do_reduce, alpha, d_var, v_inv)
}

impute_missing_Y_rcpp <- function(Y, mu, Vinv, patterns, pattern_obs) {
    .Call('_mvsusieR_impute_missing_Y_rcpp', PACKAGE = 'mvsusieR', Y, mu, Vinv, patterns, pattern_obs)
}

inner_em_rcpp <- function(llik, weights, pi_init, max_iter, tol) {
    .Call('_mvsusieR_inner_em_rcpp', PACKAGE = 'mvsusieR', llik, weights, pi_init, max_iter, tol)
}

compute_VinvR_3d_rcpp <- function(mat, Vinv_list, pattern_assign) {
    .Call('_mvsusieR_compute_VinvR_3d_rcpp', PACKAGE = 'mvsusieR', mat, Vinv_list, pattern_assign)
}

compute_XtR_3d_rcpp <- function(X_3d, R_mat, Vinv_list, pattern_assign, method, Xbar) {
    .Call('_mvsusieR_compute_XtR_3d_rcpp', PACKAGE = 'mvsusieR', X_3d, R_mat, Vinv_list, pattern_assign, method, Xbar)
}

compute_Xb_3d_rcpp <- function(X_3d, b, method, Xbar) {
    .Call('_mvsusieR_compute_Xb_3d_rcpp', PACKAGE = 'mvsusieR', X_3d, b, method, Xbar)
}

compute_betahat_3d_rcpp <- function(svs_3d, XtR) {
    .Call('_mvsusieR_compute_betahat_3d_rcpp', PACKAGE = 'mvsusieR', svs_3d, XtR)
}

compute_svs_inv_3d_rcpp <- function(Vinv_list, pattern, raw_sq_sum, raw_sum, n_k, cm, csd, method, Xbar, Vinvsum) {
    .Call('_mvsusieR_compute_svs_inv_3d_rcpp', PACKAGE = 'mvsusieR', Vinv_list, pattern, raw_sq_sum, raw_sum, n_k, cm, csd, method, Xbar, Vinvsum)
}

compute_vbxxb_rcpp <- function(alpha, mu2_3d, svs_inv_3d, d) {
    .Call('_mvsusieR_compute_vbxxb_rcpp', PACKAGE = 'mvsusieR', alpha, mu2_3d, svs_inv_3d, d)
}

compute_Xbar_from_sums_rcpp <- function(Vinv_list, pattern, raw_sum, n_k, cm, csd, Vinvsuminv) {
    .Call('_mvsusieR_compute_Xbar_from_sums_rcpp', PACKAGE = 'mvsusieR', Vinv_list, pattern, raw_sum, n_k, cm, csd, Vinvsuminv)
}

precompute_gram_xtx_rcpp <- function(pattern, raw_sq_sum, raw_sum, n_k, cm, csd) {
    .Call('_mvsusieR_precompute_gram_xtx_rcpp', PACKAGE = 'mvsusieR', pattern, raw_sq_sum, raw_sum, n_k, cm, csd)
}

